apiVersion: batch/v1
kind: Job
metadata:
  labels:
    io.kompose.service: {{ .Values.edgex_config_seed.name }}
  name: {{ .Values.edgex_config_seed.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.edgex_config_seed.name }}
    spec:
      containers:
      - image: {{ .Values.configSeedImage }}
        name: {{ .Values.edgex_config_seed.name }}
        resources: {}
        volumeMounts:
        - mountPath: {{ .Values.volumes.data_db.path }}
          name: {{ .Values.volumes.data_db.name }}
        - mountPath: {{ .Values.volumes.logs.path }}
          name: {{ .Values.volumes.logs.name }}
        - mountPath: {{ .Values.volumes.consul_config.path }}
          name: {{ .Values.volumes.consul_config.name }}
        - mountPath: {{ .Values.volumes.consul_data.path }}
          name: {{ .Values.volumes.consul_data.name }}
      restartPolicy: OnFailure
      volumes:
      - name: {{ .Values.volumes.data_db.name }}
        hostPath:
          path: {{ .Values.volumes.data_db.path }}
      - name: {{ .Values.volumes.logs.name }}
        hostPath:
          path: {{ .Values.volumes.logs.path }}
      - name: {{ .Values.volumes.consul_config.name }}
        hostPath:
          path: {{ .Values.volumes.consul_config.path }}
      - name: {{ .Values.volumes.consul_data.name }}
        hostPath:
          path: {{ .Values.volumes.consul_data.path }}
