# Default values for edgexfoundry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# images
coreCommandImage: juanman/docker-core-command-go:latest
coreConsulImage: consul:1.3.1
coreDataImage: juanman/docker-core-data-go:latest
exportClientImage: juanman/docker-export-client-go:latest
exportDistroImage: juanman/docker-export-distro-go:latest
loggingImage: juanman/docker-support-logging-go:latest
coreMetadataImage: juanman/docker-core-metadata-go:latest
mongoImage: edgexfoundry/docker-edgex-mongo:0.6.0
notificationsImage: juanman/docker-support-notifications-go:latest
schedulerImage: juanman/docker-support-scheduler-go:latest
configSeedImage: juanman/docker-core-config-seed-go:latest

volumes:
  data_db:
    name: "data-db"
    path: "/data/db"
  logs:
    name: "edgex-logs"
    path: "/edgex/logs"
  consul_config:
    name: "consul-config"
    path: "/consul/config"
  consul_data:
    name: "consul-data"
    path: "/consul/data"

edgex_config_seed:
  name: "edgex-config-seed" 

consul:
  name: "edgex-core-consul"
  ports:
    server: 8300
    cli_rpc: 8400
    https: 8443
    http: 8500
    dns: 8600

mosquitto:
    enabled: true
    name: "mosquitto"

edgex_core_command:
  name: "edgex-core-command"
  port: 48082

edgex_core_data:
  name: "edgex-core-data"
  ports:
    http: 48080
    zero_queue: 5563
    
edgex_export_client:
  name: "edgex-export-client"
  port: 48071

edgex_export_distro:
  name: "edgex-export-distro"
  ports:
    http: 48070
    analytics_queue: 5566
    message_queue: 5563

edgex_logging:
  name: "edgex-support-logging"
  port: 48061

edgex_core_metadata:
  name: "edgex-core-metadata"
  port: 48081

mongo:
  name: "edgex-mongo"
  port: 27017

edgex_notifications:
  name: "edgex-support-notifications"
  port: 48060

edgex_rules_engine:
  enabled: false
  name: "edgex-support-rulesengine"
  port: 48075

edgex_scheduler:
  name: "edgex-support-scheduler"
  port: 48085

edgex_device_mqtt:
  enabled: true
  name: "edgex-device-mqtt"
  port: 49982

defaultResources: 
  requests:
    cpu: 0

nodeSelector: {}

tolerations: []

affinity: {}

global:
  hpa:
    min: 1
    max: 10
    metric: cpu
    utilization: 80

#  namespace: default

  serviceType: LoadBalancer

  pullPolicy: Always

  probes:
    initial_delay: 5
    timeout: 1
    period: 15
    delay: 15
