# Default values for edgexfoundry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# images
#coreCommandImage: edgexfoundry/docker-core-command:0.7.0
coreCommandImage: juanman/docker-core-command::original
coreConsulImage: consul:1.3.1
#coreDataImage: edgexfoundry/docker-core-data-go:0.7.0
coreDataImage: juanman/docker-core-data:original
#exportClientImage: edgexfoundry/docker-export-client-go:0.7.0
exportClientImage: juanman/docker-export-client:original
#exportDistroImage: edgexfoundry/docker-export-distro-go:0.7.0
exportDistroImage: juanman/docker-export-distro:original
#loggingImage: edgexfoundry/docker-support-logging-go:0.7.0
loggingImage: juanman/docker-support-logging:original
coreMetadataImage: juanman/docker-core-metadata:original
#coreMetadataImage: edgexfoundry/docker-core-metadata-go:0.7.0
mongoImage: edgexfoundry/docker-edgex-mongo:0.6.0
notificationsImage: juanman/docker-support-notifications:original
#notificationsImage: edgexfoundry/docker-support-notifications-go:0.7.0
rulesEngineImage: edgexfoundry/docker-support-rulesengine:0.7.0
schedulerImage: juanman/docker-support-scheduler:original
#schedulerImage: edgexfoundry/docker-support-scheduler-go:0.7.0
deviceVirtualImage: edgexfoundry/docker-device-virtual:0.6.0
deviceMqttImage: edgexfoundry/docker-device-mqtti-go:0.7.0

volumes:
  db_data:
    name: "db-data"
    path: "/data/db"
  logs:
    name: "edgex-logs"
    path: "/edgex/logs"
  consul_config:
    name: "consul-config"
    path: "/consul/config"
  consul_data:
    name: "consul-data"
    path: "/consul/data"

consul:
  name: "edgex-core-consul"
  ports:
    cli_rpc: 8400
    http: 8500
    dns: 8600

edgex_core_command:
  name: "edgex-core-command"
  port: 48082

edgex_core_data:
  name: "edgex-core-data"
  ports:
    http: 48080
    zero_queue: 5563
    
edgex_export_client:
  name: "edgex-export-client"
  port: 48071

edgex_export_distro:
  name: "edgex-export-distro"
  ports:
    http: 48070
    analytics_queue: 5566
    message_queue: 5563

edgex_logging:
  name: "edgex-support-logging"
  port: 48061

edgex_core_metadata:
  name: "edgex-core-metadata"
  port: 48081

mongo:
  name: "edgex_mongo"
  port: 27017

edgex_notifications:
  name: "edgex-support-notifications"
  port: 48060

edgex_rules_engine:
  name: "edgex-support-rulesengine"
  port: 48075

edgex_scheduler:
  name: "edgex-support-scheduler"
  port: 48085

edgex_device_virtual:
  name: "edgex-device-virtual"
  port: 49990

edgex_device_mqtt:
  name: "edgex-device-mqtt"
  port: 49982

defaultResources: 
  requests:
    cpu: 0

nodeSelector: {}

tolerations: []

affinity: {}
