apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: edgex-device-mqtt
  name: edgex-device-mqtt
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: edgex-device-mqtt
    spec:
      containers:
      - image: juanman/docker-device-mqtt-go:prueba2
        name: edgex-device-mqtt
        ports:
        - containerPort: 49982
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /data/db
          name: data-db
        - mountPath: /edgex/logs
          name: edgex-logs
        - mountPath: /consul/config
          name: consul-config
        - mountPath: /consul/data
          name: consul-data
      restartPolicy: Always
      volumes:
      - name: data-db
        hostPath:
          path: /data/db
      - name: edgex-logs
        hostPath:
          path: /edgex/logs
      - name: consul-config
        hostPath:
          path: /consul/config
      - name: consul-data
        hostPath:
          path: /consul/data
