apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: edgex-core-metadata
  name: edgex-core-metadata
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: edgex-core-metadata
    spec:
      containers:
      - image: juanman/docker-core-metadata-go:latest
        name: edgex-core-metadata
        ports:
        - containerPort: 48081
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: data-db
        - mountPath: /edgex/logs
          name: edgex-logs
        - mountPath: /consul/config
          name: consul-config
        - mountPath: /consul/data
          name: consul-data
      restartPolicy: Always
      volumes:
      - name: data-db
        hostPath:
          path: /data/db
      - name: edgex-logs
        hostPath:
          path: /edgex/logs
      - name: consul-config
        hostPath:
          path: /consul/config
      - name: consul-data
        hostPath:
          path: /consul/data
      livenessProbe:
        httpGet:
          path: /api/v1/ping
          port: 48081
        initialDelaySeconds: 5
        periodSeconds: 5
