# Default values for edgexfoundry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# images
mosquittoImage: eclipse-mosquitto

mosquitto:
  name: "mosquitto"
  ports:
    http: 9001
    mqtt: 1883
  
