apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: edgex-core-consul
  name: edgex-core-consul
spec:
  ports:
  - name: "server"
    port: 8300
    targetPort: 8300
  - name: "rpc"
    port: 8400
    targetPort: 8400
  - name: "https"
    port: 8443
    targetPort: 8443
  - name: "http"
    port: 8500
    targetPort: 8500
  - name: "consuldns"
    port: 8600
    targetPort: 8600
  selector:
    io.kompose.service: edgex-core-consul
