apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: edgex-device-mqtt
  name: edgex-device-mqtt
spec:
  ports:
  - name: "49982"
    port: 49982
    targetPort: 49982
  selector:
    io.kompose.service: edgex-device-mqtt
